site_name: Godot Play Billing
theme:
  name: material
  logo: assets/icon_white.png
  favicon: assets/icon.png
  copyright: "Â© 2024-present Luminix Studios. All rights reserved."
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: blue
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
nav:
  - Introduction: index.md
  - Get Started:
    - Download: get-started/download.md
    - Installation: get-started/installation.md
  - Integrate Play Billing: integrate.md
  - Api Reference:
    - Home: api-reference/index.md
    - Play Billing: api-reference/play-billing.md
    - Models:
      - Purchase: api-reference/models/purchase.md
      - ProductDetail:
        - Home: api-reference/models/product-detail/index.md
        - Pricing Phase: api-reference/models/product-detail/pricing-phase.md
        - OneTimePurchaseOfferDetails: api-reference/models/product-detail/purchase-offer.md
        - InstallmentPlanDetails: api-reference/models/product-detail/installment-plan-details.md
        - SubscriptionOfferDetails: api-reference/models/product-detail/subscription-offer-details.md
  - ChangeLog: changelog.md
markdown_extensions:
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/LuminixStudios
copyright: Copyright &copy; 2024-present Luminix Studios. All rights reserved.
